const API=window.CIVICLENS_API||(
  window.location.hostname==="civiclens-dashboard.onrender.com"
    ?"https://civiclens-api-s144.onrender.com"
    :"http://localhost:8000"
);
const fmt=n=>Number(n??0).toLocaleString("en-IN");
const pct=n=>Number(n??0).toFixed(2);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
let districtRows=[]; let stateRows=[];
async function get(path){const r=await fetch(API+path);if(!r.ok)throw new Error(await r.text());return r.json();}
function setApiStatus(ok){const el=document.querySelector("#apiStatus");if(!el)return;el.className="status-pill"+(ok?" ok":"");el.innerHTML="<i></i> "+(ok?"API connected":"API unavailable");}
function renderKpis(o){const items=[["Received",fmt(o.received),"Verified receipts"],["Disposed",fmt(o.disposed),"Recorded disposals"],["Pending",fmt(o.pending),"Current workload"],["Disposal rate",pct(o.disposal_rate)+"%","Disposed ÷ received"],["181+ days",fmt(o.ageing_181_plus),"Ageing 181+ days"]];document.querySelector("#kpis").innerHTML=items.map(x=>"<div class=\"kpi\"><small>"+x[0]+"</small><strong>"+x[1]+"</strong><span>"+x[2]+"</span></div>").join("");document.querySelector("#snapshot").textContent="Snapshot "+o.snapshot_date+" · Reporting period "+o.reporting_period;}
function renderComposition(o){const received=Math.max(Number(o.received||0),1),disposed=Math.max(Number(o.disposed||0),0),pending=Math.max(Number(o.pending||0),0);const disposalAngle=Math.min(360,disposed/received*360),pendingAngle=Math.min(360,pending/Math.max(received+pending,1)*360);document.querySelector("#donut").style.background="conic-gradient(var(--teal) 0deg "+pendingAngle+"deg,#8b9bb4 "+pendingAngle+"deg "+Math.min(360,pendingAngle+disposalAngle/2)+"deg,#d97706 "+Math.min(360,pendingAngle+disposalAngle/2)+"deg 360deg)";document.querySelector("#donutValue").textContent=pct(o.pending_share)+"%";document.querySelector("#compositionLegend").innerHTML=[["Pending",pending,"Current workload"],["Disposed",disposed,"Recorded disposals"],["Received",received,"Base volume"]].map(x=>"<div class=\"legend-row\"><i></i><span>"+x[0]+" · "+x[2]+"</span><b>"+fmt(x[1])+"</b></div>").join("");}
function mergeDistrictCounts(rows){const map=new Map(rows.map(r=>[String(r.state_ut).toLowerCase(),r.district_count]));return stateRows.map(r=>{const exact=map.get(String(r.state_ut).toLowerCase());if(exact!==undefined)return {...r,district_count:exact};const normalized=String(r.state_ut).replace(/^Union Territory of /i,"").toLowerCase();const hit=rows.find(x=>String(x.state_ut).toLowerCase().includes(normalized)||normalized.includes(String(x.state_ut).toLowerCase()));return {...r,district_count:hit?.district_count??null};});}
function renderStates(rows){stateRows=rows;document.querySelector("#rows").textContent=rows.length+" matching State / UT records";document.querySelector("#table").innerHTML=rows.length?rows.map(r=>"<tr><td><strong>"+esc(r.state_ut)+"</strong></td><td>"+fmt(r.received)+"</td><td>"+fmt(r.disposed)+"</td><td>"+fmt(r.pending_total)+"</td><td>"+pct(r.disposal_rate)+"%</td><td>"+fmt(r.ageing_181_plus)+"</td><td>"+(r.district_count??"—")+"</td></tr>").join(""):"<tr><td colspan=\"7\" class=\"empty\">No State / UT records match the search.</td></tr>";}
function renderSnapshots(snaps){const box=document.querySelector("#snapshots");box.innerHTML=snaps.length?snaps.slice(0,5).map(s=>"<div class=\"snapshot-item\"><strong>"+esc(s.snapshot_date)+"</strong><span>"+esc(s.reporting_period)+"</span><small>"+fmt(s.record_count)+" State / UT records · verified registry</small></div>").join(""):"<div class=\"empty\">No registered snapshots.</div>";}
function renderAgeing(a){const items=[["0–60 days",a["0_60"]],["61–180 days",a["61_180"]],["181–365 days",a["181_365"]],["365+ days",a["365_plus"]]];const total=items.reduce((s,x)=>s+Number(x[1]||0),0);document.querySelector("#ageCards").innerHTML=items.map(x=>"<div class=\"age-card\"><span>"+x[0]+"</span><strong>"+fmt(x[1])+"</strong><em>"+(total?((x[1]/total)*100).toFixed(1):"0.0")+"% of pending</em></div>").join("");const max=Math.max(...items.map(x=>Number(x[1]||0)),1);document.querySelector("#ageChart").innerHTML=items.map(x=>"<div class=\"bar-row\"><span>"+x[0]+"</span><div class=\"bar-track\"><i style=\"width:"+Math.max(2,Number(x[1]||0)/max*100)+"%\"></i></div><b>"+fmt(x[1])+"</b></div>").join("");}
function renderGeo(coverage,rows){document.querySelector("#geoStates").textContent=fmt(rows.length);document.querySelector("#geoDistricts").textContent=fmt(coverage.total_districts);document.querySelector("#geoCoverage").textContent=coverage.district_metrics_available?"Available":"Directory only";document.querySelector("#districtCoverageNote").textContent=coverage.district_metrics_available?"Verified district grievance metrics are connected.":"LGD district directory is connected; current public CPGRAMS dashboard does not expose a public district metric table, so CIVICLENS does not manufacture district numbers.";const top=rows.slice().sort((a,b)=>b.district_count-a.district_count).slice(0,8),max=Math.max(...top.map(x=>x.district_count),1);document.querySelector("#districtBars").innerHTML=top.map(x=>"<div class=\"bar-row\"><span>"+esc(x.state_ut)+"</span><div class=\"bar-track\"><i style=\"width:"+(x.district_count/max*100)+"%\"></i></div><b>"+fmt(x.district_count)+"</b></div>").join("");}
function renderDistrictDirectory(rows){districtRows=rows;const q=(document.querySelector("#districtSearch")?.value||"").trim().toLowerCase(),filtered=q?rows.filter(r=>r.state_ut.toLowerCase().includes(q)):rows;document.querySelector("#districtTable").innerHTML=filtered.map(r=>"<tr><td><strong>"+esc(r.state_ut)+"</strong></td><td>"+fmt(r.district_count)+"</td><td>"+(r.metrics_available?"Verified":"Directory only")+"</td><td>"+esc(r.directory_report_date)+"</td></tr>").join("")||"<tr><td colspan=\"4\" class=\"empty\">No State / UT matches the directory search.</td></tr>";const select=document.querySelector("#districtState"),current=select.value;select.innerHTML=rows.map(r=>"<option value=\""+esc(r.state_ut)+"\">"+esc(r.state_ut)+" · "+fmt(r.district_count)+" districts</option>").join("");if([...select.options].some(o=>o.value===current))select.value=current;else if(rows.length)select.value=(rows.find(x=>x.state_ut==="Tamil Nadu")||rows[0]).state_ut;renderDistrictDetail();}
async function renderDistrictDetail(){const state=document.querySelector("#districtState")?.value,box=document.querySelector("#districtDetail");if(!state||!box)return;try{const d=await get("/api/v1/districts/"+encodeURIComponent(state)),available=d.metrics_available;box.innerHTML="<div class=\"district-card\"><div class=\"district-number\">"+fmt(d.district_count)+"</div><div><span>State / UT</span><b>"+esc(d.state_ut)+"</b></div><div><span>Administrative source</span><b>LGD · "+esc(d.directory_report_date)+"</b></div><div><span>CPGRAMS metric status</span><b>"+(available?"Connected":"Awaiting verified district snapshot")+"</b></div></div><div class=\"availability "+(available?"ready":"")+"\">"+(available?"District grievance metrics are available and can be analysed without deriving them from State/UT totals.":"District names/counts are verified from LGD. Current public CPGRAMS data cannot be mathematically split into districts. Add a verified district-level CPGRAMS snapshot to activate received, disposed, pending, ageing, history and district AI analytics.")+"</div>";}catch(err){box.innerHTML="<div class=\"empty error\">"+esc(err.message||"District detail unavailable.")+"</div>";}}
function renderQuality(d){const items=[["State / UT rows",d.rows],["Unique State / UT",d.unique_states_ut],["Missing numeric",d.missing_numeric_values],["Duplicate records",d.duplicate_states_ut],["Negative values",d.negative_numeric_values],["Ageing errors",d.ageing_reconciliation_errors]];document.querySelector("#quality").innerHTML=items.map(x=>"<div class=\"quality-item\"><small>"+x[0]+"</small><b>"+fmt(x[1])+"</b></div>").join("")+"<div class=\"quality-result\"><strong>✓ Dataset validation passed</strong><span>"+esc(d.snapshot_date)+" · "+esc(d.reporting_period)+" · HTTPS source: "+(d.source_is_https?"yes":"no")+"</span></div>";}
function deltaText(d){const sign=Number(d.change)>0?"+":"";return sign+Number(d.change).toLocaleString("en-IN")+(d.change_pct==null?"":" · "+sign+d.change_pct+"%");}
function renderHistory(d){const status=document.querySelector("#historyStatus"),comparison=document.querySelector("#historyComparison"),detail=document.querySelector("#historyDetail");if(d.status!=="ok"){status.textContent=d.reason;comparison.innerHTML="";detail.innerHTML="<div class=\"empty\">Add another verified snapshot to unlock comparison and state timelines.</div>";return;}status.textContent=d.from.snapshot_date+" → "+d.to.snapshot_date+" · "+d.coverage.common_states_ut+" common State / UT records";const cards=[["Received",d.aggregate.received],["Disposed",d.aggregate.disposed],["Pending",d.aggregate.pending_total],["181–365 days",d.aggregate.pending_181_365],["365+ days",d.aggregate.pending_over_365]];comparison.innerHTML=cards.map(x=>"<div class=\"comparison-card\"><small>"+x[0]+"</small><b>"+deltaText(x[1])+"</b></div>").join("");detail.innerHTML="<div class=\"history-state\"><label for=\"historyState\">Explore a State / UT timeline</label><select id=\"historyState\">"+stateRows.map(x=>"<option value=\""+esc(x.state_ut)+"\">"+esc(x.state_ut)+"</option>").join("")+"</select><div id=\"stateTimeline\"></div></div>";document.querySelector("#historyState").addEventListener("change",loadStateHistory);loadStateHistory();}
async function loadStateHistory(){const select=document.querySelector("#historyState"),box=document.querySelector("#stateTimeline");if(!select||!box)return;try{const d=await get("/api/v1/history/state/"+encodeURIComponent(select.value));if(d.status!=="ok"){box.innerHTML="<div class=\"empty\">"+esc(d.reason)+"</div>";return;}box.innerHTML="<div class=\"timeline\">"+d.timeline.map(x=>"<div class=\"timeline-item\"><span>"+esc(x.snapshot_date)+"</span><b>Pending "+fmt(x.pending_total)+"</b><small>Received "+fmt(x.received)+" · Disposed "+fmt(x.disposed)+"</small></div>").join("")+"</div>";}catch{box.innerHTML="<div class=\"empty\">State history unavailable.</div>";}}
async function loadHistory(){try{renderHistory(await get("/api/v1/history"));}catch{document.querySelector("#historyStatus").textContent="Historical registry unavailable.";}}
async function loadSuggestions(){const d=await get("/api/v1/ai/suggestions"),box=document.querySelector("#suggestions");box.innerHTML=d.suggestions.map(q=>"<button class=\"suggestion\" type=\"button\" data-q=\""+esc(q)+"\">"+esc(q)+"</button>").join("");box.querySelectorAll(".suggestion").forEach(b=>b.addEventListener("click",()=>{document.querySelector("#question").value=b.dataset.q;askAI();}));}
async function askAI(){const input=document.querySelector("#question"),out=document.querySelector("#answer"),evidence=document.querySelector("#evidence"),question=input.value.trim();if(question.length<3){out.textContent="Please enter at least 3 characters.";return;}out.textContent="Analysing verified CIVICLENS data…";evidence.textContent="Resolving deterministic analytics and grounded AI context…";try{const r=await fetch(API+"/api/v1/ai/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})}),d=await r.json();if(!r.ok)throw new Error(d.detail||"AI request failed.");out.textContent=d.answer||"No answer returned.";evidence.textContent="Evidence: "+(d.snapshot_date||"verified snapshot")+" · "+(d.reporting_period||"current period")+" · "+(d.grounding||"dataset-grounded");}catch(err){out.textContent="The AI service is temporarily unavailable. Deterministic dashboard analytics remain available.";evidence.textContent=err.message||"AI request unavailable.";}}
async function loadDashboard(search=""){const [o,states,a,snaps,coverage,directory]=await Promise.all([get("/api/v1/overview"),get("/api/v1/states?limit=100&search="+encodeURIComponent(search)),get("/api/v1/ageing"),get("/api/v1/snapshots"),get("/api/v1/districts/coverage"),get("/api/v1/districts?limit=100")]);stateRows=mergeDistrictCounts(states);renderKpis(o);renderComposition(o);renderStates(stateRows);renderAgeing(a);renderSnapshots(snaps);renderGeo(coverage,directory);renderDistrictDirectory(directory);setApiStatus(true);}
document.querySelector("#refreshBtn")?.addEventListener("click",()=>loadDashboard().catch(()=>setApiStatus(false)));
document.querySelector("#exportBtn")?.addEventListener("click",()=>window.open(API+"/api/v1/export/csv","_blank"));
document.querySelector("#districtExport")?.addEventListener("click",()=>window.open(API+"/api/v1/export/district-directory","_blank"));
document.querySelector("#districtOpen")?.addEventListener("click",()=>document.querySelector("#districtDetail")?.scrollIntoView({behavior:"smooth",block:"center"}));
document.querySelector("#districtState")?.addEventListener("change",renderDistrictDetail);
document.querySelector("#districtSearch")?.addEventListener("input",()=>renderDistrictDirectory(districtRows));
document.querySelector("#ask")?.addEventListener("click",askAI);
document.querySelector("#question")?.addEventListener("keydown",e=>{if(e.key==="Enter")askAI();});
let searchTimer;document.querySelector("#search")?.addEventListener("input",e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadDashboard(e.target.value).catch(()=>{setApiStatus(false);document.querySelector("#rows").textContent="State data unavailable.";document.querySelector("#table").innerHTML="";}),250);});
(async()=>{try{await loadDashboard();await loadSuggestions();await loadHistory();renderQuality(await get("/api/v1/data-quality"));}catch(err){console.error(err);setApiStatus(false);document.querySelector("#rows").textContent="Dashboard data is temporarily unavailable.";document.querySelector("#districtCoverageNote").textContent="API unavailable. Start the CIVICLENS backend or check the deployed API.";document.querySelector("#quality").innerHTML="<div class=\"empty error\">Data quality endpoint unavailable.</div>";}})();